config/routes.rb
Rails.application.routes.draw do
  resources :fans
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fan.rb
class Fan < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :fans
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fans_controller.rb
class FansController < ApplicationController

    before_action :set_fan, only: [:show, :edit, :update]

    def index
      @fans = Fan.all
    end

    def new
      @fan = Fan.new
    end

    def create
      @fan = Fan.create(fan_params)
      redirect_to @fan
    end

    def update
      set_fan
      @fan.update(fan_params)

      if @fan.save
        redirect_to @fan
      else
        render :edit
      end
    end

    private

    def fan_params
      params.require(:fan).permit(:name, :team_id)
    end

    def set_fan
      @fan = Fan.find(params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  before_action :set_team, only: [:show, :edit, :update]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.create(team_params)
    redirect_to @team
  end

  # def show
  #   byebug
  # end

  def update
    set_team
    @team.update(team_params)

    if @team.save
      redirect_to @team
    else
      render :edit
    end
  end

  private

  def team_params
    params.require(:team).permit(:name, :season)
  end

  def set_team
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fans_helper.rb
module FansHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/fans/edit.erb
<h1>Edit a Fan</h1>

<%= form_for @fan do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/fans/index.erb
<h1>Fan Names</h1>
<ul>
  <% @fans.each do |fan| %>
  <li><%= link_to fan.name, fan %></li>
  <% end %>
</ul>

app/views/fans/new.erb
<h1>Create a Fan</h1>

<%= form_for @fan do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.collection_select :team_id, Team.all, :id, :name%>
  <br>
  <%= f.submit %>
<% end %>

app/views/fans/show.erb
<h1><%= @fan.name %></h1>
<p><%= link_to @fan.team.name, team_path(@fan.team) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fandom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>